version: "3.8"

services:
  app:
    container_name: graph-docker
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: $PORT # Change to your real port
        DB_MAIN: $DB_MAIN # Your DB URL here
    environment:
      PORT: $PORT # Should match build args
      DB_MAIN: $DB_MAIN # Your DB URL here
    ports:
      - "$PORT:$PORT" # host:container
    restart: always
    command: ["npm", "run", "start"]

networks:
  default:
    driver: host
