version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: $PORT # Change to your real port
        DB_MAIN: $DB_MAIN # Your DB URL here
    container_name: graph-docker
    ports:
      - "$PORT:$PORT" # host:container
    environment:
      PORT: $PORT # Should match build args
      DB_MAIN: $DB_MAIN # Your DB URL here
    restart: always
    command: ["npm", "run", "start"]
