scalar JSON
scalar JSONObject

type Book {
  title: String
  author: String
}

type Mutation {
  login(username: String!, password: String!): String
  testSubscription(str: String): Boolean
}

type Subscription {
  newOrderPending: String
}

type Query {
  books: [Book]
  userList(offset: Int = 0, limit: Int = 25, roles: [Int]): [User]
  user(id: Int!): User
  me: User
}

type User {
  id: Int!
  display: String
  contact: String
  gender: String
  role: Role
  createdDate: String
  isActive: Boolean
}

type Role {
  id: Int
  name: String
}

enum Gender {
  MALE
  FEMALE
  OTHER
}
