extend type Query {
  getAttendanceStaff(
    limit: Int = 25
    offset: Int = 0
    from: String
    to: String
  ): JSON
  getAttendanceAdmin(limit: Int = 25, offset: Int = 0): JSON
}

extend type Mutation {
  checkAttendance(userId: Int!, date: String!): Boolean
}
