extend type Query {
  getAttendanceStaff(
    limit: Int = 25
    offset: Int = 0
    from: String
    to: String
  ): [Attendance]
  attendanceListAdmin(
    limit: Int = 31
    offset: Int = 0
    month: Int!
    year: Int!
  ): [Attendance]
  getAttendanceStaffToday(date: String!): Attendance
  getSummaryAttendanceStaff(userId: Int!): JSON
  attendanceStaff(userId: Int!, from: String, to: String): [Attendance]
  activityStaff(userId: Int!): JSON
}

extend type Mutation {
  checkAttendance(userId: Int!, date: String!): Boolean
}

type Attendance {
  id: Int
  user: User
  checkIn: String
  checkOut: String
  overTimeIn: String
  overTimeOut: String
  checkDate: String
  leave: Leave
}
