extend type Mutation {
  createOrder(data: OrderInput): Boolean
  changeOrderStatus(data: ChangeOrderInput): Boolean
}

extend type Query {
  orderList(offset: Int = 0, limit: Int = 25): [Order]
  order(id: Int, token: String): Order
}

type Order {
  id: Int
  name: String
  address: String
  set: String
  status: StatusOrder
  uuid: String
  items: [OrderItem]
  total: String
  paid: String
}

type OrderItem {
  id: Int
  sku: SKU
  price: Float
  qty: Int
  discount: Float
  status: StatusOrderItem
}

input OrderInput {
  name: String
  uuid: String
  address: String
  set: String
  carts: [CartItemInput]
}

input CartItemInput {
  skuId: Int
  productId: Int
  price: Float
  qty: Int
  discount: Float
  addons: String
  remark: String
}

input ChangeOrderInput {
  orderId: Int!
  id: Int
  status: StatusOrder
  itemStatus: StatusOrderItem
}

enum StatusOrder {
  PENDING
  VERIFY
  DELIVERY
  CHECKOUT
}

enum StatusOrderItem {
  PENDING
  MAKING
  OUT_OF_STOCK
  REQUEST_CHANGE
  COMPLETED
}
