extend type Query {
  orderBalanceSummary(from: String, to: String): JSON
  topProductSell(
    from: String
    to: String
    limit: Int = 10
    categoryIds: [Int]
  ): [ProductSell]
  reportStaffPayroll(from: String, to: String): JSON
  reportSaleByDay(from: String, to: String): JSON
  reportSaleProduct(
    from: String
    to: String
    filters: ReportSaleFilter
    groupBy: ReportSaleGroupBy = PRODUCT
  ): JSON
}

input ReportSaleFilter {
  category: [Int]
}

type ProductSell {
  product: Product
  sku: SKU
  qty: Int
  total: Float
}

enum ReportSaleGroupBy {
  PRODUCT
  DATE
}
